export type Lang = { name: string, hljs?: string, mime?: string }

export const langMap: {
  [key: string]: Lang
} = {
  txt: { name: 'Plain Text', hljs: 'plaintext' },
  asm: { name: 'Assembly', hljs: 'x86asm', mime: 'text/x-asm' },
  bat: { name: 'Batchfile', hljs: 'dos' },
  c: { name: 'C', hljs: 'c', mime: 'text/x-c' },
  cbl: { name: 'COBOL', hljs: 'cobol' },
  clj: { name: 'Clojure', hljs: 'clojure', mime: 'text/x-clojure' },
  cmake: { name: 'CMake', hljs: 'cmake' },
  coffee: { name: 'CoffeeScript', hljs: 'coffeescript', mime: 'application/vnd.coffeescript' },
  cpp: { name: 'C++', hljs: 'cpp', mime: 'text/x-c++src' },
  cs: { name: 'C#', hljs: 'csharp', mime: 'text/x-csharp' },
  css: { name: 'CSS', hljs: 'css', mime: 'text/css' },
  csv: { name: 'CSV' },
  dart: { name: 'Dart', hljs: 'dart', mime: 'text/x-dart' },
  dm: { name: 'DM' },
  dockerfile: { name: 'Dockerfile', hljs: 'dockerfile' },
  erl: { name: 'Erlang', hljs: 'erlang', mime: 'text/x-erlang' },
  ex: { name: 'Elixir', hljs: 'elixir', mime: 'text/x-elixir' },
  f90: { name: 'Fortran', hljs: 'fortran', mime: 'text/x-fortran' },
  go: { name: 'Go', hljs: 'go', mime: 'text/x-go' },
  groovy: { name: 'Groovy', hljs: 'groovy', mime: 'text/x-groovy' },
  hs: { name: 'Haskell', hljs: 'haskell', mime: 'text/x-haskell' },
  html: { name: 'HTML', hljs: 'xml', mime: 'text/html' },
  ini: { name: 'INI', hljs: 'ini' },
  java: { name: 'Java', hljs: 'java', mime: 'text/x-java' },
  jl: { name: 'Julia', hljs: 'julia' },
  js: { name: 'JavaScript', hljs: 'javascript', mime: 'text/javascript' },
  json: { name: 'JSON', hljs: 'json', mime: 'application/json' },
  kt: { name: 'Kotlin', hljs: 'kotlin', mime: 'text/x-kotlin' },
  lisp: { name: 'Lisp', hljs: 'lisp', mime: 'text/x-common-lisp' },
  lua: { name: 'Lua', hljs: 'lua', mime: 'text/x-lua' },
  makefile: { name: 'Makefile', hljs: 'makefile' },
  matlab: { name: 'Matlab', hljs: 'matlab' },
  md: { name: 'Markdown', hljs: 'markdown', mime: 'text/markdown' },
  ml: { name: 'OCaml', hljs: 'ocaml', mime: 'text/x-ocaml' },
  mm: { name: 'Objective-C', hljs: 'objectivec', mime: 'text/x-objcsrc' },
  pas: { name: 'Pascal', hljs: 'delphi', mime: 'text/x-pascal' },
  php: { name: 'PHP', hljs: 'php', mime: 'application/x-php' },
  pm: { name: 'Perl', hljs: 'perl', mime: 'application/x-perl' },
  pro: { name: 'Prolog', hljs: 'prolog' },
  ps1: { name: 'PowerShell', hljs: 'powershell' },
  py: { name: 'Python', hljs: 'python', mime: 'text/x-python' },
  r: { name: 'R', hljs: 'r' },
  rb: { name: 'Ruby', hljs: 'ruby', mime: 'application/x-ruby' },
  rs: { name: 'Rust', hljs: 'rust', mime: 'text/rust' },
  scala: { name: 'Scala', hljs: 'scala', mime: 'text/x-scala' },
  sh: { name: 'Shell', hljs: 'bash', mime: 'application/x-shellscript' },
  sql: { name: 'SQL', hljs: 'sql', mime: 'application/sql' },
  swift: { name: 'Swift', hljs: 'swift' },
  tex: { name: 'TeX', hljs: 'latex', mime: 'text/x-tex' },
  toml: { name: 'TOML', hljs: 'ini', mime: 'application/toml' },
  ts: { name: 'TypeScript', hljs: 'typescript' },
  v: { name: 'Verilog', hljs: 'verilog', mime: 'text/x-verilog' },
  vba: { name: 'Visual Basic', hljs: 'vbscript', mime: 'text/vbscript' },
  xml: { name: 'XML', hljs: 'xml', mime: 'application/xml' },
  yaml: { name: 'YAML', hljs: 'yaml', mime: 'text/x-yaml' }
}
